// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7xu6_Ia7ChBr1zzKwtUr3LS6JMhdOizs',
    appId: '1:77125335004:web:e10a10c047c98014e6c119',
    messagingSenderId: '77125335004',
    projectId: 'dtoro-dev',
    authDomain: 'dtoro-dev.firebaseapp.com',
    storageBucket: 'dtoro-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmLbqlAJ0_Oe-fr1kwdAVIGC_XC6az42w',
    appId: '1:77125335004:android:1aba0243063ed4ffe6c119',
    messagingSenderId: '77125335004',
    projectId: 'dtoro-dev',
    storageBucket: 'dtoro-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9XJt_ljoJuSEJrmeDUKJQF3APiKXKogk',
    appId: '1:77125335004:ios:41e0f2b228d0b6fae6c119',
    messagingSenderId: '77125335004',
    projectId: 'dtoro-dev',
    storageBucket: 'dtoro-dev.firebasestorage.app',
    iosClientId: '77125335004-logupkr4lreooo5qgai0ul3g4ttebrul.apps.googleusercontent.com',
    iosBundleId: 'us.dtoro.app',
  );

}